default_agent: test1
agents:
  test1:
    name: test1
    language: python
    node_version: '20'
    entrypoint: /Users/steven/Development/GitHub/aws-bedrock/agent/runtime.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/steven/Development/GitHub/aws-bedrock/agent
    aws:
      execution_role: arn:aws:iam::526908180591:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-1b4f0e9851
      execution_role_auto_create: false
      account: '526908180591'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-526908180591-us-west-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: test1-EuRGp04eDi
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:526908180591:runtime/test1-EuRGp04eDi
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: test1_mem-I8j8aXEO2U
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:526908180591:memory/test1_mem-I8j8aXEO2U
      memory_name: test1_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
